### ISSUE TITLE
关于软件许可证和商业使用

### ISSUE THREAD

**Issue by gloomy-ghost** [Hello-hao/Tbed#13]
看到 README 里面声明「不得作为盈利商业使用」，然而项目用的是 LGPL，路过提醒下开发者可能有什么误解。
首先自由软件许可证都是不限制商业使用的，只要遵守许可证中的条件就不构成侵权。开发者可以另外提供不同条件的商业授权，但用户也可以选择通过自由软件许可证来使用。建议转成条件最严格的 AGPL 许可证，这样至少可以要求定制 SaaS 的商业用户贡献回修改，也给另外的商业授权留了些后路。
如果铁心要禁商业使用的话，建议重起一份许可证，不过注意无法回溯修改目前为止已经用 LGPL 发布的版本。
声明：我不是律师，以上为一般性参考信息，不是专业法律建议。

**Comment by Hello-hao** [comment]
谢谢你的提醒和建议，我会认真了解一下各项许可。做进一步的更正处理。
