### ISSUE TITLE
关于cookies过期时间的问题

### ISSUE THREAD

**Issue by Creling** [Hello-hao/Tbed#17]
目前hellohao的cookies过期时间是“会话”，意味着只要关闭浏览器，cookies就会失效。
禁用了游客上传后，目前的cookies策略导致上传图片前需要频繁重新登录，希望作者大大可以稍作改善，比如设置过期时间为7天/15天。

**Comment by Hello-hao** [comment]
页面半个小时无操作，就会过期、

**Comment by Creling** [comment]
> 
> 
> 页面半个小时无操作，就会过期、

感觉这个时间还是太短了，作者大大可以稍微延长一些吗？否则对于禁用游客上传的用户而言非常不方便。
