### ISSUE TITLE
游客上传的问题

### ISSUE THREAD

**Issue by hueralin** [Hello-hao/Tbed#21]
使用了几个小时，发现了一些小问题：
1. 禁止了游客上传，且是在登录状态，可上传完图片，后台显示是游客上传的。
2. 有时登录了，右侧导航栏也显示“控制面板”（即已登录状态），可是上传时显示“已禁止游客上传”（即把我当成了未登录状态），不过多刷新几次就可以了，不知是否是session过期导致的。

emmm，有新增用户的功能么？
不知未来是否有上传图片到不同目录的功能呢？

总的来说，很棒，对目前的我来说，功能完全够用！

**Comment by Hello-hao** [comment]
你反馈的这个问题有可能是缓存导致的，建议吧Nginx缓存关了。详情参考官方文档。
