### ISSUE TITLE
用一些不常见的邮箱注册会报错

### ISSUE THREAD

**Issue by xun-mi-git** [Hello-hao/Tbed#41]
使用邮箱: `xunmiemail@vip.qq.com`会报错,显示服务器500
![寻觅_20213123023159](https://user-images.githubusercontent.com/43723838/138545497-fc76f086-cbd4-4664-8ca2-0ea8300c2844.png)
如果我使用 `xunmiemail@qq.com` 即可正常注册

**Comment by Hello-hao** [comment]
重构版已经修改了，你可以试一下。如果有问题 告诉我 我再来调整。
