### ISSUE TITLE
请问，这个系统可以一个用户自主选择多个存储点吗

### ISSUE THREAD

**Issue by 1378056564** [Hello-hao/Tbed#43]
最近想搞个图床系统
为爱发电
然后想着就是想看看有没有图床系统ui符合自己的想法
又功能比较细致
大致来看，imgurl买了捐赠版，开发者说三月份会更新，不知道能怎么样
兰空2.0，但是似乎也没有标题的功能
然后GitHub推了大佬的这个。仔细看了看文档，十分详细
ui与大致功能挺符合我的所想
所以就提出标题的问题。想咨询是否已经有了单用户多存储口，以及多鉴黄口等功能。或者说后续会开发。
十分感谢大佬的努力

**Comment by Hello-hao** [comment]
目前不可以，存储源是管理员在后台设置的。上传者无法自行选择。不过感谢你的意见，后期我会酌情考虑适配此功能。

**Comment by Hello-hao** [comment]
多鉴黄口接口目前Core版本已经支持两个。开源版目前只有一个。

**Comment by 1378056564** [comment]
感谢大佬百忙之中的回复，已经购买core版本～晚上搭建试试，希望越来越好
