### ISSUE TITLE
/admin界面的个性设置里API文档部分与后端代码的实现好像不一致

### ISSUE THREAD

**Issue by YuanNing-96** [Hello-hao/Tbed#46]
/admin界面的个性设置里的API文档的请求地址后面为：/api/uploadbymail/
但是后端代码里貌似没有/api的部分，只有/uploadbymail的部分，位置是在ClientController.class里
@PostMapping(value = "/uploadbymail")
只有这一个url相关的注解，类上也没有/api的注解

api请求返回情况：
请求/api/uploadbymail/时，响应码为404
请求/uploadbymail时，响应码为200，返回值为{"code":"500","info":"未知错误"}。（返回值暂时不是重点，只是展示一下有返回值）

**Comment by Hello-hao** [comment]
报错信息方便附上报错的整体截图吗？顺便说明报错的触发条件等
