### ISSUE TITLE
群辉docker下用docker-compose一键式安装，无法显示验证码

### ISSUE THREAD

**Issue by kingcard1131** [Hello-hao/Tbed#60]
安装的是免费版
日志如下：
![image](https://user-images.githubusercontent.com/53737003/235299558-013277e8-383f-4a55-93d1-d0c941e99844.png)

**Comment by kingcard1131** [comment]
复制出来有乱码，所以贴的图片

**Comment by Hello-hao** [comment]
验证码不能显示是因为redis没有正确启动的问题

**Comment by Zhen-Bo** [comment]
雖然不知道是不是同原因
不過我也是在 Synology 上使用會產生跟樓主一樣的錯誤
機型: DS1621+
DSM: 7.2 - 64561
套件版本: container manager 20.10.23-1405
frontend subdomain: pic
backend subdomain: pic-server
域名託管商: cloudflare free
router: WRX 560
port frowarding: only 443

步驟:
1. dsm 自帶的 nginx 設定 proxy
  - pic -> 10089
  - pic-server -> 10089
2. 使用控制台內工具向 let's encrypt 申請兩個憑證, pic 子域名的對應 pic, pic-server 子域名的對應 pic-server
3. 訪問 pic 子域名(前端), 有兩個打像後端的 api 被阻擋, 顯示錯誤 mixed-content
  - http://pic-server.example.com/webInfo
  - http://pic-server.example.com/getUploadInfo
![image](https://github.com/Hello-hao/Tbed/assets/30999421/a61fe6e8-0426-4072-b60a-1328ed63fc31)

可能造成原因:
docker-compose 中
- HELLOHAO_WEB_HOST
- HELLOHAO_SERVER_HOST
兩個參數預設是http, 使用了群暉的人自然而然都會使用 https 造成再 https 發送 http 請求導致被阻擋

項目建議(小弟不才, 頂級前端雲玩家的想法):
加一個 fallback 機制, 發現 http 或 https 請求被阻擋後嘗試多發送一次另外的協議嘗試
或是不綁死協議, 直接請使用者填入後子域名+域名

**Comment by Zhen-Bo** [comment]
抱歉開太多 issue 頁面
剛剛發到另一個 issue 了

**Comment by Zhen-Bo** [comment]
![image](https://github.com/Hello-hao/Tbed/assets/30999421/80ea4a2b-cfbc-4553-9f78-965768e3a058)
修改完 env 的 https 後成功進入

**Comment by kingcard1131** [comment]
> ![image](https://user-images.githubusercontent.com/30999421/242316171-80ea4a2b-cfbc-4553-9f78-965768e3a058.png) 修改完 env 的 https 後成功進入

兄弟，请问最终是这么解决的？是将yml文件中的您提到的
HELLOHAO_WEB_HOST
HELLOHAO_SERVER_HOST
https改回默认的http吗？

**Comment by Zhen-Bo** [comment]
> > ![image](https://user-images.githubusercontent.com/30999421/242316171-80ea4a2b-cfbc-4553-9f78-965768e3a058.png) 修改完 env 的 https 後成功進入
> 
> 兄弟，请问最终是这么解决的？是将yml文件中的您提到的 HELLOHAO_WEB_HOST HELLOHAO_SERVER_HOST https改回默认的http吗？

是的, 因為前端好像無法從 https 發 request 到 http
反正你只要把你的前端跟後端統一協議就好

**Comment by kingcard1131** [comment]
> > > ![image](https://user-images.githubusercontent.com/30999421/242316171-80ea4a2b-cfbc-4553-9f78-965768e3a058.png) 修改完 env 的 https 後成功進入
> > 
> > 
> > 兄弟，请问最终是这么解决的？是将yml文件中的您提到的 HELLOHAO_WEB_HOST HELLOHAO_SERVER_HOST https改回默认的http吗？
> 
> 是的, 因為前端好像無法從 https 發 request 到 http 反正你只要把你的前端跟後端統一協議就好

我改回去（http）也不行，不知道为啥。然后我给前后盾域名都加证书变成https也不行。还是提示服务器请求错误。我怀疑就是因为服务器请求错误导致的无法显示验证码

**Comment by kingcard1131** [comment]
> 雖然不知道是不是同原因 不過我也是在 Synology 上使用會產生跟樓主一樣的錯誤 機型: DS1621+ DSM: 7.2 - 64561 套件版本: container manager 20.10.23-1405 frontend subdomain: pic backend subdomain: pic-server 域名託管商: cloudflare free router: WRX 560 port frowarding: only 443
> 
> 步驟:
> 
> 1. dsm 自帶的 nginx 設定 proxy
> 
> * pic -> 10089
> * pic-server -> 10089
> 
> 2. 使用控制台內工具向 let's encrypt 申請兩個憑證, pic 子域名的對應 pic, pic-server 子域名的對應 pic-server
> 3. 訪問 pic 子域名(前端), 有兩個打像後端的 api 被阻擋, 顯示錯誤 mixed-content
> 
> * http://pic-server.example.com/webInfo
> * http://pic-server.example.com/getUploadInfo
>   ![image](https://user-images.githubusercontent.com/30999421/242314377-a61fe6e8-0426-4072-b60a-1328ed63fc31.png)
> 
> 可能造成原因: docker-compose 中
> 
> * HELLOHAO_WEB_HOST
> * HELLOHAO_SERVER_HOST
>   兩個參數預設是http, 使用了群暉的人自然而然都會使用 https 造成再 https 發送 http 請求導致被阻擋
> 
> 項目建議(小弟不才, 頂級前端雲玩家的想法):
> 
> 1. 加一個 fallback 機制, 發現 http 或 https 請求被阻擋後嘗試多發送一次另外的協議嘗試
> 2. 不綁死協議, 直接請使用者填入後子域名+域名
> 3. 不綁域名, 直接請使用者自行做 reverse proxy

我们的问题似乎一样：这是我网页的报错，您的解决方法没看懂，能不能具体说一下，谢谢
![KBT0T8DC5K%J~~OU CA0NJW](https://github.com/Hello-hao/Tbed/assets/53737003/2fb3650c-295b-404c-b516-1cd0f43b639f)

**Comment by Zhen-Bo** [comment]
> > 雖然不知道是不是同原因 不過我也是在 Synology 上使用會產生跟樓主一樣的錯誤 機型: DS1621+ DSM: 7.2 - 64561 套件版本: container manager 20.10.23-1405 frontend subdomain: pic backend subdomain: pic-server 域名託管商: cloudflare free router: WRX 560 port frowarding: only 443
> > 步驟:
> > 
> > 1. dsm 自帶的 nginx 設定 proxy
> > 
> > 
> > * pic -> 10089
> > * pic-server -> 10089
> > 
> > 
> > 2. 使用控制台內工具向 let's encrypt 申請兩個憑證, pic 子域名的對應 pic, pic-server 子域名的對應 pic-server
> > 3. 訪問 pic 子域名(前端), 有兩個打像後端的 api 被阻擋, 顯示錯誤 mixed-content
> > 
> > 
> > * http://pic-server.example.com/webInfo
> > * http://pic-server.example.com/getUploadInfo
> >   ![image](https://user-images.githubusercontent.com/30999421/242314377-a61fe6e8-0426-4072-b60a-1328ed63fc31.png)
> > 
> > 可能造成原因: docker-compose 中
> > 
> > * HELLOHAO_WEB_HOST
> > * HELLOHAO_SERVER_HOST
> >   兩個參數預設是http, 使用了群暉的人自然而然都會使用 https 造成再 https 發送 http 請求導致被阻擋
> > 
> > 項目建議(小弟不才, 頂級前端雲玩家的想法):
> > 
> > 1. 加一個 fallback 機制, 發現 http 或 https 請求被阻擋後嘗試多發送一次另外的協議嘗試
> > 2. 不綁死協議, 直接請使用者填入後子域名+域名
> > 3. 不綁域名, 直接請使用者自行做 reverse proxy
> 
> 我们的问题似乎一样：这是我网页的报错，您的解决方法没看懂，能不能具体说一下，谢谢 ![KBT0T8DC5K%J~~OU CA0NJW](https://user-images.githubusercontent.com/53737003/268632152-2fb3650c-295b-404c-b516-1cd0f43b639f.png)

你的 docker-compose 把 http 換成 https 就好了
錯誤訊息是說你嘗試在https協議的域名中發起 http request (你後端的連結是 http)
還有真想解決請一併把 docker-compose 附上, 我大學通靈課被當沒法幫你通靈出你是怎麼配置的...

**Comment by kingcard1131** [comment]
> > 雖然不知道是不是同原因 不過我也是在 Synology 上使用會產生跟樓主一樣的錯誤 機型: DS1621+ DSM: 7.2 - 64561 套件版本: container manager 20.10.23-1405 frontend subdomain: pic backend subdomain: pic-server 域名託管商: cloudflare free router: WRX 560 port frowarding: only 443
> > 步驟:
> > 
> > 1. dsm 自帶的 nginx 設定 proxy
> > 
> > 
> > * pic -> 10089
> > * pic-server -> 10089
> > 
> > 
> > 2. 使用控制台內工具向 let's encrypt 申請兩個憑證, pic 子域名的對應 pic, pic-server 子域名的對應 pic-server
> > 3. 訪問 pic 子域名(前端), 有兩個打像後端的 api 被阻擋, 顯示錯誤 mixed-content
> > 
> > 
> > * http://pic-server.example.com/webInfo
> > * http://pic-server.example.com/getUploadInfo
> >   ![image](https://user-images.githubusercontent.com/30999421/242314377-a61fe6e8-0426-4072-b60a-1328ed63fc31.png)
> > 
> > 可能造成原因: docker-compose 中
> > 
> > * HELLOHAO_WEB_HOST
> > * HELLOHAO_SERVER_HOST
> >   兩個參數預設是http, 使用了群暉的人自然而然都會使用 https 造成再 https 發送 http 請求導致被阻擋
> > 
> > 項目建議(小弟不才, 頂級前端雲玩家的想法):
> > 
> > 1. 加一個 fallback 機制, 發現 http 或 https 請求被阻擋後嘗試多發送一次另外的協議嘗試
> > 2. 不綁死協議, 直接請使用者填入後子域名+域名
> > 3. 不綁域名, 直接請使用者自行做 reverse proxy
> 
> 我们的问题似乎一样：这是我网页的报错，您的解决方法没看懂，能不能具体说一下，谢谢 ![KBT0T8DC5K%J~~OU CA0NJW](https://user-images.githubusercontent.com/53737003/268632152-2fb3650c-295b-404c-b516-1cd0f43b639f.png)

我将http改为https也不行。我的两个域名指向了同一个IP地址，我是在互联网访问的。可以通过域名加端口的方式访问后端。前端访问就是连接不上后端。
![image](https://github.com/Hello-hao/Tbed/assets/53737003/e0afe46b-1d9b-41e6-9fef-994ca60b52ea)

我尝试了多种方案，错误似乎越来越多，改为https后：
![image](https://github.com/Hello-hao/Tbed/assets/53737003/d2678a3d-2109-4677-a67f-3cddd4a07c13)
单独通过域名加端口的方式访问后端：可以正常访问

![image](https://github.com/Hello-hao/Tbed/assets/53737003/067a721a-34f9-43e5-ad20-c6832830df13)

以上访问均通过互联网远程进行

**Comment by Zhen-Bo** [comment]
> > > 雖然不知道是不是同原因 不過我也是在 Synology 上使用會產生跟樓主一樣的錯誤 機型: DS1621+ DSM: 7.2 - 64561 套件版本: container manager 20.10.23-1405 frontend subdomain: pic backend subdomain: pic-server 域名託管商: cloudflare free router: WRX 560 port frowarding: only 443
> > > 步驟:
> > > 
> > > 1. dsm 自帶的 nginx 設定 proxy
> > > 
> > > 
> > > * pic -> 10089
> > > * pic-server -> 10089
> > > 
> > > 
> > > 2. 使用控制台內工具向 let's encrypt 申請兩個憑證, pic 子域名的對應 pic, pic-server 子域名的對應 pic-server
> > > 3. 訪問 pic 子域名(前端), 有兩個打像後端的 api 被阻擋, 顯示錯誤 mixed-content
> > > 
> > > 
> > > * http://pic-server.example.com/webInfo
> > > * http://pic-server.example.com/getUploadInfo
> > >   ![image](https://user-images.githubusercontent.com/30999421/242314377-a61fe6e8-0426-4072-b60a-1328ed63fc31.png)
> > > 
> > > 可能造成原因: docker-compose 中
> > > 
> > > * HELLOHAO_WEB_HOST
> > > * HELLOHAO_SERVER_HOST
> > >   兩個參數預設是http, 使用了群暉的人自然而然都會使用 https 造成再 https 發送 http 請求導致被阻擋
> > > 
> > > 項目建議(小弟不才, 頂級前端雲玩家的想法):
> > > 
> > > 1. 加一個 fallback 機制, 發現 http 或 https 請求被阻擋後嘗試多發送一次另外的協議嘗試
> > > 2. 不綁死協議, 直接請使用者填入後子域名+域名
> > > 3. 不綁域名, 直接請使用者自行做 reverse proxy
> > 
> > 
> > 我们的问题似乎一样：这是我网页的报错，您的解决方法没看懂，能不能具体说一下，谢谢 ![KBT0T8DC5K%J~~OU CA0NJW](https://user-images.githubusercontent.com/53737003/268632152-2fb3650c-295b-404c-b516-1cd0f43b639f.png)
> 
> 我将http改为https也不行。我的两个域名指向了同一个IP地址，我是在互联网访问的。可以通过域名加端口的方式访问后端。前端访问就是连接不上后端。 ![image](https://user-images.githubusercontent.com/53737003/268815185-e0afe46b-1d9b-41e6-9fef-994ca60b52ea.png)
> 
> 我尝试了多种方案，错误似乎越来越多，改为https后： ![image](https://user-images.githubusercontent.com/53737003/268815321-d2678a3d-2109-4677-a67f-3cddd4a07c13.png) 单独通过域名加端口的方式访问后端：可以正常访问
> 
> ![image](https://user-images.githubusercontent.com/53737003/268815421-067a721a-34f9-43e5-ad20-c6832830df13.png)
> 
> 以上访问均通过互联网远程进行

你的DSM...有去設定 reverse proxy 嗎?
![image](https://github.com/Hello-hao/Tbed/assets/30999421/321691b8-e006-4f61-9cfd-fafcc074eff5)
沒有的話, 你的 hellohao 子域名他會去訪問你的 443 port
但問題仁加開的後端是在 10089 port
所以你填網址+port 號可以正常訪問
沒填 port 號當然不能訪問
簡單來說網址=你的 ip
https 協議 + ip = 連線到你 nas 的 443 端口
https 協議 + ip + port 號 = 連線到你 nas 上填寫的 port 號端口

**Comment by kingcard1131** [comment]
有添加反代里：如下：这样设置是否合适？我在你的截图里没有看到前端的反代？后端应该是在10088port？
![image](https://github.com/Hello-hao/Tbed/assets/53737003/50556be1-f04b-4649-ba52-a63cbd03c461)
按照图示的设置（反代里http->http，同时yml文件改为http），目前的问题是出现了跨域问题：
![image](https://github.com/Hello-hao/Tbed/assets/53737003/3cf510ea-41b1-43a2-bbf0-73ec4652b35e)
如果改为(反代理http->https，同时yml文件改为https),  则是我上午回复的截图中的问题

**Comment by kingcard1131** [comment]
我昨晚又尝试了两个新的域名，全不加证书的。我把信息公开，如果方便的话你帮我访问一下前端，看下能否发现问题
前端：http://hellohao-web.lqhy.top:53089
后端：http://hellohao-server.lqhy.top:53088
群辉反代里配置：
![image](https://github.com/Hello-hao/Tbed/assets/53737003/7f6ef62c-5a55-4ec0-b176-fd488e9f99ed)
yml配置：
![image](https://github.com/Hello-hao/Tbed/assets/53737003/692751a8-ee00-48ff-b7a0-bba5b309817f)
前端访问报错：
![image](https://github.com/Hello-hao/Tbed/assets/53737003/df5b3425-3e99-4b40-a581-20f3fb6b2244)
实在是困惑，不知道是哪里的问题

**Comment by kingcard1131** [comment]
谢谢解答，我发现是我的yml文件中的域名没有加端口号导致的。现在出现新问题，虽然不是错误，但是有这个提示：
这个http的外部链接。还有我的主页是不显示logo的，不知道和这个有关系没
![image](https://github.com/Hello-hao/Tbed/assets/53737003/a8c64cf3-cf4a-4da4-bdcd-f50ea756d866)

**Comment by kingcard1131** [comment]
多谢回复，找到原因了，是因为配置文件里域名没加端口号，可以正常访问和注册了。但是开始上传图片无法显示，经过admin账户设置存储位置后，无法上传，问题好多，不折腾了！

**Comment by YourReligion** [comment]
> 验证码不能显示是因为redis没有正确启动的问题

确实在日志中看到Redis未正常启动,但怎样解决呢

**Comment by Hello-hao** [comment]
收到了你的问题，docker镜像我已经修复了redis不能正常启动的情况，**请你删除本地的镜像**，重新拉取 `20240102` 版本的镜像进行部署即可。

**Comment by YourReligion** [comment]
> 收到了你的问题，docker镜像我已经修复了redis不能正常启动的情况，**请你删除本地的镜像**，重新拉取 `20240102` 版本的镜像进行部署即可。

非常感谢回复, 但我这边情况有些特殊, 是安装 `20240102` 出现redis无法启动, 现安装 `20230925` 反而可以正常运行
