### ISSUE TITLE
無法添加 S3 協議作為儲存源

### ISSUE THREAD

**Issue by Zhen-Bo** [Hello-hao/Tbed#63]
透過 s3 提供的bucket 的 AccessKey, SecretKey 跟 RESTful Endpoint
無法正常加入處存源

填寫參數:
AccessKey={key}
SecretKey={key}
Endpoint=0
地区=
桶名称=hellohao
存储目录=/
请求域名={S3 提供的 RESTful 端點}
策略名称=S3协议

點擊保存的時候會顯示 
![image](https://github.com/Hello-hao/Tbed/assets/30999421/97359813-6762-4b21-a47b-c1f21a1ddcff)

已確定端點有一個名稱一模一樣的 bucket

/admin/root/updateStorage 
response:
```
{
  "code": "4002",
  "info": "对象存储初始化失败,请检查参数是否正确",
  "data": null,
  "exceptions": null
}
```

平台: docker
版本: Tbed开源版 v20230622

**Comment by Hello-hao** [comment]
如果你确定你的S3信息无误，并且可以用其他三方工具正常链接，那么你可以将这个s3协议的提供给我，我来做验证修复

**Comment by Zhen-Bo** [comment]
使用的是 Synology Object storage

**Comment by Hello-hao** [comment]
经测试，本程序的S3协议可以正常对接Synology Object storage，如果你不能对接，请检查自己填写的信息是否正确或找存储源商家对接文档解决。
